version: "3"
services:
    nginx : 
        image: 
            nginx:stable-alpine
        ports: 
            - "3000:80"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro 
    node-app:
        build: .
        environment: 
            - PORT=3000
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=markan
            - MONGO_INITDB_ROOT_PASSWORD=markan1312
        volumes: 
            - mongo-db:/data/db
    redis: 
        image: redis

volumes: 
    mongo-db:
